# Generated by Django 6.0.2 on 2026-02-15 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=50)),
                ('full_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assessment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('PARTIAL', 'Partially Compliant'), ('PENDING', 'Pending Assessment')], default='PENDING', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('report_path', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
                ('assessed_against', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_records', to='auditor.framework')),
            ],
        ),
        migrations.CreateModel(
            name='CSF',
            fields=[
            ],
            options={
                'verbose_name': 'NIST CSF Framework',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditor.framework',),
        ),
        migrations.CreateModel(
            name='ECC',
            fields=[
            ],
            options={
                'verbose_name': 'ECC Framework',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditor.framework',),
        ),
        migrations.CreateModel(
            name='ISO_IEC27001',
            fields=[
            ],
            options={
                'verbose_name': 'ISO/IEC 27001 Framework',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auditor.framework',),
        ),
    ]
