# Generated by Django 6.0.2 on 2026-02-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
